name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: pwd
        run: pwd

      - name: ls
        run: ls

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
